from .core import Op


class TensorOp(Op):
  """One statement, still stated over whole tensors.

  This is the level the control-flow graph works at and the level the export
  description speaks: a destination, a few operands with their index maps, a
  scale factor, and whether the value is accumulated. It says what is to be
  computed and not how, so it is also the level an external generator can take
  a statement away at -- a `lower()` that never runs is a statement someone
  else is generating.

  `result` and `terms` are tensor descriptions as the code generators hand
  them over: a name, an index tuple, a memory layout, an equivalent sparsity
  pattern and a datatype.
  """

  def __init__(self, result, terms, alpha=1.0, add=False, loopRanges=None):
    self.result = result
    self.terms = list(terms)
    #: What the value is scaled by: a number, or the name of a scalar the
    #: kernel is given.
    self.alpha = alpha
    #: Accumulate into the destination rather than overwrite it.
    self.add = add
    #: index name -> Range, the space the statement runs over.
    self.loopRanges = dict(loopRanges) if loopRanges else {}

  def lower(self):
    """The statement as loops and scalar operations."""
    raise NotImplementedError(
      f'{type(self).__name__} is still generated by its own backend and has no '
      f'lowering yet.')

  def __repr__(self):
    return f'{type(self).__name__}({self.result.name})'


class Copy(TensorOp):
  """``result <op>= alpha * term`` over the same indices."""

  def lower(self):
    from .lower import lowerScaleAdd
    return lowerScaleAdd(self)


class Transpose(Copy):
  """The same, with the operand's axes in another order."""


class Broadcast(Copy):
  """The same, with the operand lacking indices the destination has.

  A missing index is not addressed on the operand, so the same entry is read
  for every value of it.
  """


class LoopOverGEMM(TensorOp):
  """A contraction of two operands, run as a loop over matrix products."""


class Elementwise(TensorOp):
  """An operation applied entry by entry over one index space."""


class Reduction(TensorOp):
  """An operation folding one index of its operand away."""
