from .core import Op


class TensorOp(Op):
  """One statement, still stated over whole tensors.

  This is the level the control-flow graph works at and the level the export
  description speaks: a destination, a few operands with their index maps, a
  scale factor, and whether the value is accumulated. It says what is to be
  computed and not how, so it is also the level an external generator can take
  a statement away at -- a `lower()` that never runs is a statement someone
  else is generating.

  `result` and `terms` are tensor descriptions as the code generators hand
  them over: a name, an index tuple, a memory layout, an equivalent sparsity
  pattern and a datatype. An operand may also be an immediate the operation
  was written with, in which case it is a number.
  """

  def __init__(self, result, terms, alpha=1.0, add=False, loopRanges=None,
               unrolled=False):
    self.result = result
    self.terms = list(terms)
    #: What the value is scaled by: a number, or the name of a scalar the
    #: kernel is given.
    self.alpha = alpha
    #: Accumulate into the destination rather than overwrite it.
    self.add = add
    #: index name -> Range, the space the statement runs over.
    self.loopRanges = dict(loopRanges) if loopRanges else {}
    #: Run over the entries rather than over the ranges. A sparse layout has
    #: an address for an entry and none for an index, so a statement that
    #: touches one has to name the entries it visits.
    self.unrolled = unrolled

  def lower(self):
    """The statement as loops and scalar operations."""
    raise NotImplementedError(
      f'{type(self).__name__} is still generated by its own backend and has no '
      f'lowering yet.')

  def __repr__(self):
    return f'{type(self).__name__}({self.result.name})'


class Copy(TensorOp):
  """``result <op>= alpha * term`` over the same indices."""

  def lower(self):
    from .lower import lowerScaleAdd
    return lowerScaleAdd(self)


class Transpose(Copy):
  """The same, with the operand's axes in another order."""


class Broadcast(Copy):
  """The same, with the operand lacking indices the destination has.

  A missing index is not addressed on the operand, so the same entry is read
  for every value of it.
  """


class Elementwise(TensorOp):
  """An operation applied entry by entry over one index space."""

  def __init__(self, result, terms, optype, alpha=1.0, add=False,
               loopRanges=None, unrolled=False):
    super().__init__(result, terms, alpha, add, loopRanges, unrolled)
    self.optype = optype

  def lower(self):
    from .lower import lowerElementwise
    return lowerElementwise(self)


class FusedElementwise(TensorOp):
  """Several element-wise steps over one index space.

  A member states its operation, which of its operands come from an earlier
  member, and what it scales by. What a member computes and a later one reads
  never leaves the nest, so it is a value of the loop body rather than a
  buffer.
  """

  def __init__(self, result, members, alpha=1.0, add=False, loopRanges=None):
    terms = [term for member in members for term in member.terms
             if term is not None]
    super().__init__(result, terms, alpha, add, loopRanges)
    self.members = list(members)

  def lower(self):
    from .lower import lowerFusedElementwise
    return lowerFusedElementwise(self)


class LoopOverGEMM(TensorOp):
  """A contraction of two operands, run as a loop over matrix products."""


class Reduction(TensorOp):
  """An operation folding one index of its operand away."""
