from .core import Op


class TensorOp(Op):
  """One statement, still stated over whole tensors.

  This is the level the control-flow graph works at and the level the export
  description speaks: a destination, a few operands with their index maps, a
  scale factor, and whether the value is accumulated. It says what is to be
  computed and not how, so it is also the level an external generator can take
  a statement away at -- a `lower()` that never runs is a statement someone
  else is generating.

  `result` and `terms` are tensor descriptions as the code generators hand
  them over: a name, an index tuple, a memory layout, an equivalent sparsity
  pattern and a datatype. An operand may also be an immediate the operation
  was written with, in which case it is a number.
  """

  def __init__(self, result, terms, alpha=1.0, add=False, loopRanges=None,
               unrolled=False, generator=None):
    self.result = result
    self.terms = list(terms)
    #: What the value is scaled by: a number, or the name of a scalar the
    #: kernel is given.
    self.alpha = alpha
    #: Accumulate into the destination rather than overwrite it.
    self.add = add
    #: index name -> Range, the space the statement runs over.
    self.loopRanges = dict(loopRanges) if loopRanges else {}
    #: Run over the entries rather than over the ranges. A sparse layout has
    #: an address for an entry and none for an index, so a statement that
    #: touches one has to name the entries it visits.
    self.unrolled = unrolled
    #: The backend that has claimed this statement. Which one that is falls
    #: out of what the statement is and what it is generated for; what it
    #: writes -- loops put here in the statement's place, or the statement
    #: itself, straight into the kernel -- is settled when the statement is
    #: lowered, which happens to the region and not while it is built.
    self.generator = generator

  def lower(self):
    """The statement as loops and scalar operations."""
    raise NotImplementedError(
      f'{type(self).__name__} is still generated by its own backend and has no '
      f'lowering yet.')

  def __repr__(self):
    return f'{type(self).__name__}({self.result.name})'


class Copy(TensorOp):
  """``result <op>= alpha * term`` over the same indices."""

  def lower(self):
    from .lower import lowerScaleAdd
    return lowerScaleAdd(self)


class Transpose(Copy):
  """The same, with the operand's axes in another order."""


class Broadcast(Copy):
  """The same, with the operand lacking indices the destination has.

  A missing index is not addressed on the operand, so the same entry is read
  for every value of it.
  """


class Elementwise(TensorOp):
  """An operation applied entry by entry over one index space."""

  def __init__(self, result, terms, optype, alpha=1.0, add=False,
               loopRanges=None, unrolled=False, generator=None):
    super().__init__(result, terms, alpha, add, loopRanges, unrolled, generator)
    self.optype = optype

  def lower(self):
    from .lower import lowerElementwise
    return lowerElementwise(self)


class LoopOverGEMM(TensorOp):
  """A contraction of two operands, run as a loop over matrix products."""


class Reduction(TensorOp):
  """An operation folding one index of its operand away."""

  def __init__(self, result, terms, optype, sumIndex, sumRange, alpha=1.0,
               add=False, loopRanges=None, generator=None):
    super().__init__(result, terms, alpha, add, loopRanges, generator=generator)
    self.optype = optype
    #: The index that is folded away, which the destination does not have.
    self.sumIndex = str(sumIndex)
    #: The range that index runs over.
    self.sumRange = sumRange

  def lower(self):
    from .lower import lowerReduction
    return lowerReduction(self)
